// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MembershipCreate
 */
export type MembershipCreate = {
    role: Role;
    scope_type: ScopeType;
    /**
     * Team Id
     */
    team_id?: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Workspace Id
     */
    workspace_id?: string | null;
};

/**
 * MembershipOut
 */
export type MembershipOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Org Id
     */
    org_id: string;
    role: Role;
    scope_type: ScopeType;
    /**
     * Team Id
     */
    team_id: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string | null;
};

/**
 * OrgCreate
 */
export type OrgCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner Display Name
     */
    owner_display_name: string;
    /**
     * Owner Email
     *
     * The first owner. A Keycloak user is created for this address.
     */
    owner_email: string;
};

/**
 * OrgCreated
 */
export type OrgCreated = {
    org: OrgOut;
    owner: UserOut;
};

/**
 * OrgOut
 */
export type OrgOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    status: OrgStatus;
};

/**
 * OrgStatus
 */
export type OrgStatus = 'pending' | 'active';

/**
 * Page[MembershipOut]
 */
export type PageMembershipOut = {
    /**
     * Items
     */
    items: Array<MembershipOut>;
    /**
     * Next After
     */
    next_after?: string | null;
};

/**
 * Page[OrgOut]
 */
export type PageOrgOut = {
    /**
     * Items
     */
    items: Array<OrgOut>;
    /**
     * Next After
     */
    next_after?: string | null;
};

/**
 * Page[TeamOut]
 */
export type PageTeamOut = {
    /**
     * Items
     */
    items: Array<TeamOut>;
    /**
     * Next After
     */
    next_after?: string | null;
};

/**
 * Page[UserOut]
 */
export type PageUserOut = {
    /**
     * Items
     */
    items: Array<UserOut>;
    /**
     * Next After
     */
    next_after?: string | null;
};

/**
 * Page[WorkspaceOut]
 */
export type PageWorkspaceOut = {
    /**
     * Items
     */
    items: Array<WorkspaceOut>;
    /**
     * Next After
     */
    next_after?: string | null;
};

/**
 * Role
 */
export type Role = 'owner' | 'admin' | 'billing_admin' | 'member' | 'viewer';

/**
 * ScopeType
 */
export type ScopeType = 'org' | 'workspace' | 'team';

/**
 * Status
 */
export type Status = {
    /**
     * Status
     */
    status: string;
};

/**
 * TeamCreate
 */
export type TeamCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * TeamOut
 */
export type TeamOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Org Id
     */
    org_id: string;
    /**
     * Workspace Id
     */
    workspace_id: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Org Id
     */
    org_id: string;
    status: UserStatus;
};

/**
 * UserStatus
 */
export type UserStatus = 'pending' | 'active' | 'disabled';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkspaceCreate
 */
export type WorkspaceCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * WorkspaceOut
 */
export type WorkspaceOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Org Id
     */
    org_id: string;
};

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * Successful Response
     */
    200: Status;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzErrors = {
    /**
     * Not ready
     */
    503: Status;
};

export type ReadyzError = ReadyzErrors[keyof ReadyzErrors];

export type ReadyzResponses = {
    /**
     * Successful Response
     */
    200: Status;
};

export type ReadyzResponse = ReadyzResponses[keyof ReadyzResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/orgs';
};

export type ListOrgsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * Successful Response
     */
    200: PageOrgOut;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type CreateOrgData = {
    body: OrgCreate;
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type CreateOrgErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOrgError = CreateOrgErrors[keyof CreateOrgErrors];

export type CreateOrgResponses = {
    /**
     * Successful Response
     */
    201: OrgCreated;
    /**
     * Accepted; identity provisioning is pending
     */
    202: OrgCreated;
};

export type CreateOrgResponse = CreateOrgResponses[keyof CreateOrgResponses];

export type GetOrgData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}';
};

export type GetOrgErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * Successful Response
     */
    200: OrgOut;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type ListMembershipsData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * User Id
         */
        user_id?: string | null;
        /**
         * Scope Type
         */
        scope_type?: ScopeType | null;
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/orgs/{org_id}/memberships';
};

export type ListMembershipsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMembershipsError = ListMembershipsErrors[keyof ListMembershipsErrors];

export type ListMembershipsResponses = {
    /**
     * Successful Response
     */
    200: PageMembershipOut;
};

export type ListMembershipsResponse = ListMembershipsResponses[keyof ListMembershipsResponses];

export type CreateMembershipData = {
    body: MembershipCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/memberships';
};

export type CreateMembershipErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMembershipError = CreateMembershipErrors[keyof CreateMembershipErrors];

export type CreateMembershipResponses = {
    /**
     * Successful Response
     */
    201: MembershipOut;
};

export type CreateMembershipResponse = CreateMembershipResponses[keyof CreateMembershipResponses];

export type ListUsersData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/orgs/{org_id}/users';
};

export type ListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: PageUserOut;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserOut;
    /**
     * Accepted; identity provisioning is pending
     */
    202: UserOut;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type ListWorkspacesData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: {
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/orgs/{org_id}/workspaces';
};

export type ListWorkspacesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkspacesError = ListWorkspacesErrors[keyof ListWorkspacesErrors];

export type ListWorkspacesResponses = {
    /**
     * Successful Response
     */
    200: PageWorkspaceOut;
};

export type ListWorkspacesResponse = ListWorkspacesResponses[keyof ListWorkspacesResponses];

export type CreateWorkspaceData = {
    body: WorkspaceCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/workspaces';
};

export type CreateWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkspaceError = CreateWorkspaceErrors[keyof CreateWorkspaceErrors];

export type CreateWorkspaceResponses = {
    /**
     * Successful Response
     */
    201: WorkspaceOut;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/workspaces/{workspace_id}';
};

export type GetWorkspaceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkspaceError = GetWorkspaceErrors[keyof GetWorkspaceErrors];

export type GetWorkspaceResponses = {
    /**
     * Successful Response
     */
    200: WorkspaceOut;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type ListTeamsData = {
    body?: never;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: {
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/orgs/{org_id}/workspaces/{workspace_id}/teams';
};

export type ListTeamsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTeamsError = ListTeamsErrors[keyof ListTeamsErrors];

export type ListTeamsResponses = {
    /**
     * Successful Response
     */
    200: PageTeamOut;
};

export type ListTeamsResponse = ListTeamsResponses[keyof ListTeamsResponses];

export type CreateTeamData = {
    body: TeamCreate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
        /**
         * Workspace Id
         */
        workspace_id: string;
    };
    query?: never;
    url: '/v1/orgs/{org_id}/workspaces/{workspace_id}/teams';
};

export type CreateTeamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTeamError = CreateTeamErrors[keyof CreateTeamErrors];

export type CreateTeamResponses = {
    /**
     * Successful Response
     */
    201: TeamOut;
};

export type CreateTeamResponse = CreateTeamResponses[keyof CreateTeamResponses];
