"""Orgs, workspaces, teams, users, memberships, operators, audit; row-level security.

Revision ID: 0001
Revises:
Create Date: 2026-10-09 23:33:32.843180
"""

import os
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Login roles the policies name. Created outside migrations (dev:
# deploy/compose/controlplane/controlplane-db.sql; production: infrastructure).
APP_ROLE = os.environ.get("PURSER_DB_APP_ROLE", "purser_cp_app")
SWEEPER_ROLE = os.environ.get("PURSER_DB_SWEEPER_ROLE", "purser_cp_sweeper")
S = "controlplane"

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("actor_sub", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "actor_kind IN ('operator', 'user', 'system')", name=op.f("ck_audit_events_actor_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        schema="controlplane",
    )
    op.create_index(
        "ix_audit_events_org_id_at",
        "audit_events",
        ["org_id", "at"],
        unique=False,
        schema="controlplane",
    )
    op.create_table(
        "orgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("keycloak_org_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'active' OR keycloak_org_id IS NOT NULL", name=op.f("ck_orgs_active_linked")
        ),
        sa.CheckConstraint("status IN ('pending', 'active')", name=op.f("ck_orgs_status")),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 200", name=op.f("ck_orgs_name_length")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orgs")),
        sa.UniqueConstraint("keycloak_org_id", name=op.f("uq_orgs_keycloak_org_id")),
        schema="controlplane",
    )
    op.create_table(
        "platform_operators",
        sa.Column("keycloak_sub", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("keycloak_sub", name=op.f("pk_platform_operators")),
        schema="controlplane",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("keycloak_sub", sa.UUID(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'pending' OR keycloak_sub IS NOT NULL",
            name=op.f("ck_users_linked_unless_pending"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'disabled')", name=op.f("ck_users_status")
        ),
        sa.CheckConstraint(
            "char_length(display_name) BETWEEN 1 AND 200", name=op.f("ck_users_display_name_length")
        ),
        sa.CheckConstraint(
            "email = lower(email) AND char_length(email) BETWEEN 3 AND 320",
            name=op.f("ck_users_email_form"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["controlplane.orgs.id"],
            name=op.f("fk_users_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("keycloak_sub", name=op.f("uq_users_keycloak_sub")),
        sa.UniqueConstraint("org_id", "email", name=op.f("uq_users_org_id_email")),
        sa.UniqueConstraint("org_id", "id", name=op.f("uq_users_org_id_id")),
        schema="controlplane",
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 200", name=op.f("ck_workspaces_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["controlplane.orgs.id"],
            name=op.f("fk_workspaces_org_id_orgs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("org_id", "id", name=op.f("uq_workspaces_org_id_id")),
        sa.UniqueConstraint("org_id", "name", name=op.f("uq_workspaces_org_id_name")),
        schema="controlplane",
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 200", name=op.f("ck_teams_name_length")
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "workspace_id"],
            ["controlplane.workspaces.org_id", "controlplane.workspaces.id"],
            name=op.f("fk_teams_org_id_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint(
            "org_id", "workspace_id", "id", name=op.f("uq_teams_org_id_workspace_id_id")
        ),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_teams_workspace_id_name")),
        schema="controlplane",
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("scope_type", sa.String(length=16), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'org' AND workspace_id IS NULL AND team_id IS NULL)"
            " OR (scope_type = 'workspace' AND workspace_id IS NOT NULL AND team_id IS NULL)"
            " OR (scope_type = 'team' AND workspace_id IS NOT NULL AND team_id IS NOT NULL)",
            name=op.f("ck_memberships_scope_columns"),
        ),
        sa.CheckConstraint(
            "role <> 'owner' OR scope_type = 'org'", name=op.f("ck_memberships_owner_at_org_scope")
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'billing_admin', 'member', 'viewer')",
            name=op.f("ck_memberships_role"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('org', 'workspace', 'team')", name=op.f("ck_memberships_scope_type")
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "user_id"],
            ["controlplane.users.org_id", "controlplane.users.id"],
            name=op.f("fk_memberships_org_id_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "workspace_id", "team_id"],
            [
                "controlplane.teams.org_id",
                "controlplane.teams.workspace_id",
                "controlplane.teams.id",
            ],
            name=op.f("fk_memberships_org_id_workspace_id_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "workspace_id"],
            ["controlplane.workspaces.org_id", "controlplane.workspaces.id"],
            name=op.f("fk_memberships_org_id_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        schema="controlplane",
    )
    op.create_index(
        "ix_memberships_org_id_user_id",
        "memberships",
        ["org_id", "user_id"],
        unique=False,
        schema="controlplane",
    )
    op.create_index(
        "uq_memberships_grant",
        "memberships",
        ["user_id", "role", "scope_type", "workspace_id", "team_id"],
        unique=True,
        schema="controlplane",
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###
    _row_level_security()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memberships_grant",
        table_name="memberships",
        schema="controlplane",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index("ix_memberships_org_id_user_id", table_name="memberships", schema="controlplane")
    op.drop_table("memberships", schema="controlplane")
    op.drop_table("teams", schema="controlplane")
    op.drop_table("workspaces", schema="controlplane")
    op.drop_table("users", schema="controlplane")
    op.drop_table("platform_operators", schema="controlplane")
    op.drop_table("orgs", schema="controlplane")
    op.drop_index("ix_audit_events_org_id_at", table_name="audit_events", schema="controlplane")
    op.drop_table("audit_events", schema="controlplane")
    # ### end Alembic commands ###
    # After the tables: their policies depend on these functions.
    op.execute(f"DROP FUNCTION {S}.current_org_id()")
    op.execute(f"DROP FUNCTION {S}.current_operator_is_valid()")


ORG_SCOPED = {
    # table: column holding the row's org
    "orgs": "id",
    "workspaces": "org_id",
    "teams": "org_id",
    "users": "org_id",
    "memberships": "org_id",
    "audit_events": "org_id",
}


def _row_level_security() -> None:
    """Row-level security (A5, defense in depth behind the API's own checks).

    The API's role sees a row only when the transaction has set purser.org_id
    to that row's org (with set_config(..., true), i.e. SET LOCAL), or, for the
    few operator policies, when purser.operator_sub names a row in
    platform_operators. With neither set, it sees nothing. The owner role is
    not subject to these policies (RLS is enabled, not forced) and runs only
    migrations and the bootstrap CLI.
    """
    app, sweeper = f'"{APP_ROLE}"', f'"{SWEEPER_ROLE}"'

    op.execute(f"""
        CREATE FUNCTION {S}.current_org_id() RETURNS uuid
        LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog AS
        $$ SELECT nullif(current_setting('purser.org_id', true), '')::uuid $$
    """)
    op.execute(f"""
        CREATE FUNCTION {S}.current_operator_is_valid() RETURNS boolean
        LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog AS
        $$ SELECT EXISTS (
             SELECT 1 FROM {S}.platform_operators
             WHERE keycloak_sub::text = nullif(current_setting('purser.operator_sub', true), '')
           ) $$
    """)
    op.execute(f"REVOKE ALL ON FUNCTION {S}.current_org_id() FROM PUBLIC")
    op.execute(f"REVOKE ALL ON FUNCTION {S}.current_operator_is_valid() FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION {S}.current_org_id() TO {app}")
    op.execute(f"GRANT EXECUTE ON FUNCTION {S}.current_operator_is_valid() TO {app}")

    # Least privilege: the API never deletes; the sweeper sees pending rows only.
    grants = {
        "orgs": "SELECT, INSERT, UPDATE",
        "workspaces": "SELECT, INSERT",
        "teams": "SELECT, INSERT",
        "users": "SELECT, INSERT, UPDATE",
        "memberships": "SELECT, INSERT",
        "audit_events": "INSERT",
        "platform_operators": "SELECT",
    }
    for table, privileges in grants.items():
        op.execute(f"GRANT {privileges} ON {S}.{table} TO {app}")
    op.execute(
        f"GRANT SELECT (id, status, keycloak_org_id, created_at),"
        f" UPDATE (status, keycloak_org_id, updated_at), DELETE ON {S}.orgs TO {sweeper}"
    )
    op.execute(
        f"GRANT SELECT (id, org_id, status, keycloak_sub, created_at),"
        f" UPDATE (status, keycloak_sub, updated_at), DELETE ON {S}.users TO {sweeper}"
    )

    for table, column in ORG_SCOPED.items():
        op.execute(f"ALTER TABLE {S}.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY org_isolation ON {S}.{table} TO {app}
            USING ({column} = {S}.current_org_id())
            WITH CHECK ({column} = {S}.current_org_id())
        """)

    operator = f"{S}.current_operator_is_valid()"
    for table, commands in {
        "orgs": ("SELECT", "INSERT", "UPDATE"),
        "users": ("SELECT", "INSERT"),
        "memberships": ("SELECT", "INSERT"),
        "audit_events": ("INSERT",),
    }.items():
        for command in commands:
            name = f"operator_{command.lower()}"
            if command == "INSERT":
                clause = f"WITH CHECK ({operator})"
            elif command == "UPDATE":
                clause = f"USING ({operator}) WITH CHECK ({operator})"
            else:
                clause = f"USING ({operator})"
            op.execute(f"CREATE POLICY {name} ON {S}.{table} FOR {command} TO {app} {clause}")
    # Activating the first owner of an org an operator just created.
    op.execute(f"""
        CREATE POLICY operator_activate_pending ON {S}.users FOR UPDATE TO {app}
        USING ({operator} AND status = 'pending') WITH CHECK ({operator})
    """)

    # The sweeper reads identifiers of every org and user (its column grants
    # above keep names and emails out of reach) and changes or deletes only
    # pending rows. Reads aren't limited to pending rows because Postgres checks
    # an updated row against the SELECT policy too, so activating a row needs it.
    for table in ("orgs", "users"):
        op.execute(
            f"CREATE POLICY sweeper_read ON {S}.{table} FOR SELECT TO {sweeper} USING (true)"
        )
    for table in ("orgs", "users"):
        op.execute(f"""
            CREATE POLICY sweeper_finish ON {S}.{table} FOR UPDATE TO {sweeper}
            USING (status = 'pending') WITH CHECK (status IN ('pending', 'active'))
        """)
        op.execute(
            f"CREATE POLICY sweeper_rollback ON {S}.{table} FOR DELETE TO {sweeper}"
            " USING (status = 'pending')"
        )
    # The sweeper audits what it finishes or rolls back, as the system.
    op.execute(f"GRANT INSERT ON {S}.audit_events TO {sweeper}")
    op.execute(
        f"CREATE POLICY sweeper_audit ON {S}.audit_events FOR INSERT TO {sweeper}"
        " WITH CHECK (actor_kind = 'system')"
    )
